# ---
# sources:
#   jkBS: https://github.com/hh-lohmann/jekyll-basal-scaffold,
#   jekyllGitHub:
#     used version:  https://github.com/jekyll/jekyll/blob/495456bb3cf5e53992af1a395120a4a37b676be8/lib/site_template/_config.yml
#     latest version: https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml
# references:
#   jekyllDocs: https://jekyllrb.com/docs/configuration/
# ---
#
#
# # "Core settings" for Jekyll (build, globals, collections, defaults)
# 
#     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#        Changing settings here requires a new build (jekyll b / jekyll s)
#     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#
# # Build options
#
# ## Excludes
#
# Files that must be present in the source directory, but must not be output

exclude:
  - LICENSE
  - README.md

# ## No .sass-cache
#
# Prevent default .sass-cache directory in the source directory to keep things clear

sass:
  cache: false

# # Global variables
#
# ## Permalink
#
# see 
#
# permalink: ....


# Collections
# see https://jekyllrb.com/docs/collections/#collections
# !! permalink in Abhängigkeit von collection => Front Matter Defaults: scope
collections:
  roadmap:
    output: true
    permalink: /:categories/:title/


# # Front Matter Defaults
#
# see https://jekyllrb.com/docs/configuration/front-matter-defaults/
#
#


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: main

